Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Style/FrozenStringLiteralComment:
  Enabled: false

ClassLength:
  Max: 150

Metrics/BlockLength:
  Max: 25
